Repository AY2223S1-CS2103T-W16-1/tp, pull requests merged in 2022-11, with the labels that each got.

#195 Update PPP
  docs/team/jehousoh.md
Labels: documentation, priority.Low, type.Task

#198 Update room field
  src/main/java/seedu/guest/model/guest/Request.java
  src/main/java/seedu/guest/model/guest/Room.java
  src/test/java/seedu/guest/model/guest/RoomTest.java
Labels: type.Bug, priority.Medium, type.Task, severity.Medium, must fix

#199 Improve user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MarkRoomsUncleanActivityDiagram.puml
  docs/images/MarkRoomsUncleanActivityDiagram.png
  docs/team/bryanhce.md
  src/main/java/seedu/guest/logic/commands/MarkRoomsUncleanCommand.java
  src/main/java/seedu/guest/model/guest/Email.java
Labels: type.Bug, documentation

#200 Make format consistent on pdf version
  docs/UserGuide.md
Labels: documentation, priority.Medium

#201 Format fix for UG for html
  docs/UserGuide.md
Labels: documentation

#202 Update PPP, Lan Jingbo Part
  docs/team/lan-jingbo.md
Labels: documentation, priority.Medium

#203 Fix Backslashes to forward slashes
  src/main/java/seedu/guest/model/GuestBook.java
  src/main/java/seedu/guest/model/guest/DateRange.java
Labels: type.Bug, severity.VeryLow, good to fix

#205 Fix edit Request true blank problem
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
Labels: type.Bug, priority.Low, good to fix

#204 Fix Singular Word Error
  src/main/java/seedu/guest/commons/core/Messages.java
Labels: type.Bug, severity.VeryLow, good to fix

#209 add request test
  src/main/java/seedu/guest/model/guest/Request.java
  src/test/java/seedu/guest/model/guest/RequestTest.java
Labels: priority.Medium, type.Task

#207 Fix user guide
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task, good to fix

#206 Update field constraints
  docs/UserGuide.md
  src/main/java/seedu/guest/model/guest/Bill.java
  src/main/java/seedu/guest/model/guest/DateRange.java
  src/main/java/seedu/guest/model/guest/Name.java
  src/main/java/seedu/guest/model/guest/Phone.java
  src/main/java/seedu/guest/model/guest/Request.java
  src/test/java/seedu/guest/model/guest/NameTest.java
Labels: documentation

#212 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/ProposedImplementationFindActivityDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/FindActivityDiagram.png
  docs/team/bryanhce.md
  docs/team/kangzongxian.md
Labels: documentation, priority.Medium, type.Task

#215 Update Justin PPP
  docs/team/justinpeng13.md
Labels: documentation, priority.Low, type.Task

#214 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bryanhce.md
  docs/team/jehousoh.md
  docs/team/kangzongxian.md
  docs/team/lan-jingbo.md
  guestbook.json
Labels: documentation

#211 Restrict bill max value to prevent rounding error
  docs/UserGuide.md
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/main/java/seedu/guest/model/guest/Bill.java
  src/test/java/seedu/guest/logic/commands/BillCommandTest.java
  src/test/java/seedu/guest/model/guest/BillTest.java
Labels: type.Bug, severity.Medium, must fix

#213 Bug fixes
  build.gradle
  docs/DeveloperGuide.md
  docs/images/GuestBookIcon.png
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
Labels: documentation, priority.Medium, type.Task

#217 Change download image to be less glaring
  docs/images/DownloadInstruction.png
Labels: documentation, priority.Low, type.Task

#219 Update Ui photos
  docs/images/Ui.png
  docs/images/UiComponentLabels.png
  docs/images/findAlex9927275803-68.png
Labels: documentation, priority.Medium, type.Task

#220 Final standardisation to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#221 Fix UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/guest/model/guest/Email.java
Labels: type.Bug, documentation, severity.Medium

#223 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium, type.Task

#224 Update my ppp
  docs/team/kangzongxian.md
Labels: documentation, priority.Low, type.Task

#225 Improve format of UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#226 Fixing html div in table
  docs/UserGuide.md
Labels: documentation

#227 Update PPP
  docs/team/jehousoh.md
Labels: documentation

#228 Finalise PPP
  docs/team/bryanhce.md
Labels: documentation

#229 Add more manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/lan-jingbo.md
Labels: documentation, type.Story, priority.Medium

#231 Justin PPP
  docs/team/justinpeng13.md
Labels: documentation, priority.Low

#232 Final edits ug
  docs/UserGuide.md
Labels: documentation

#233 Ensuring the pdf conversion page break is proper
  docs/UserGuide.md
Labels: documentation

#234 Removing additional whitespace
  docs/UserGuide.md
Labels: documentation
