Repository AY2223S1-CS2103T-W16-1/tp, pull requests merged in 2022-10, with the labels that each got.

#59 Update Ui.png
  docs/images/Ui.png
Labels: documentation, priority.High

#63 Update names of files
  docs/AboutUs.md
  docs/images/lan-jingbo.png
  docs/team/lan-jingbo.md
Labels: documentation, priority.High

#65 Add number of guests
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/NumberOfGuests.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/GuestBookParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/GuestBookTest.java
  src/test/java/seedu/guest/model/guest/GuestTest.java
  src/test/java/seedu/guest/model/guest/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/guest/model/guest/NumberOfGuestsTest.java
  src/test/java/seedu/guest/model/guest/UniqueGuestBookTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/PersonUtil.java
  src/test/java/seedu/guest/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#66 Refactor commons and logic test cases
  src/test/java/seedu/guest/commons/core/index/IndexTest.java
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandTest.java
  src/test/java/seedu/guest/logic/commands/ClearCommandTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
  src/test/java/seedu/guest/logic/commands/FindCommandTest.java
  src/test/java/seedu/guest/logic/commands/ListCommandTest.java
Labels: priority.High, type.Task

#69 Fix test cases
  src/test/java/seedu/guest/logic/commands/AddCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.High

#68 Added date range field to guests
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/DateRange.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/guest/DateRangeTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/PersonUtil.java
  src/test/java/seedu/guest/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#70 Delete address and tag fields
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/Address.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/tag/Tag.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/storage/JsonAdaptedTag.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonGuestBookStorageTest/invalidAndValidGuestGuestBook.json
  src/test/data/JsonGuestBookStorageTest/invalidGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/invalidGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/GuestBookTest.java
  src/test/java/seedu/guest/model/guest/AddressTest.java
  src/test/java/seedu/guest/model/guest/GuestTest.java
  src/test/java/seedu/guest/model/guest/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/guest/model/guest/UniqueGuestBookTest.java
  src/test/java/seedu/guest/model/tag/TagTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/PersonUtil.java
  src/test/java/seedu/guest/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#74 Re-factored test cases and class names
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/guest/logic/commands/ClearCommandTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/commands/FindCommandTest.java
  src/test/java/seedu/guest/logic/commands/ListCommandTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/GuestBookParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/GuestBookTest.java
  src/test/java/seedu/guest/model/ModelManagerTest.java
  src/test/java/seedu/guest/model/guest/GuestTest.java
  src/test/java/seedu/guest/model/guest/UniqueGuestBookTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/storage/JsonGuestBookStorageTest.java
  src/test/java/seedu/guest/storage/JsonSerializableGuestBookTest.java
  src/test/java/seedu/guest/storage/StorageManagerTest.java
  src/test/java/seedu/guest/testutil/AddressBookBuilder.java
  src/test/java/seedu/guest/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBookBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/GuestUtil.java
  src/test/java/seedu/guest/testutil/TestUtil.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
  src/test/java/seedu/guest/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#80 Update documentation to reflect date range and user stories
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation, priority.Medium, type.Task

#95 Add new field isRoomClean
  docs/UserGuide.md
  guestbook.json
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/IsRoomClean.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/guest/IsRoomCleanTest.java
  src/test/java/seedu/guest/model/util/SampleDataUtilTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/GuestUtil.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#100 Add bill field to Guest
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/Bill.java
  src/main/java/seedu/guest/model/guest/DateRange.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/NumberOfGuests.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/guest/BillTest.java
  src/test/java/seedu/guest/model/guest/DateRangeTest.java
  src/test/java/seedu/guest/model/util/SampleDataUtilTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#103 Add additional test cases for bill and validation message
  src/main/java/seedu/guest/model/guest/Bill.java
  src/test/java/seedu/guest/model/guest/BillTest.java
Labels: priority.Medium, type.Task

#105 Enable assertion
  build.gradle
Labels: severity.Medium

#104 Add bill command
  docs/UserGuide.md
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/main/java/seedu/guest/logic/parser/BillCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/GuestBookParser.java
  src/main/java/seedu/guest/model/guest/Bill.java
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/commands/BillCommandTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/parser/BillCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/guest/BillTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#102 Add new field Room
  docs/UserGuide.md
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/Room.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/guest/RoomTest.java
  src/test/java/seedu/guest/model/util/SampleDataUtilTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/GuestUtil.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#109 Update DG (Ui and Implementation)
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/EditActivityDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#113 Add implementation of MarkRoomsUnclean command to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/MarkRoomsUncleanActivityDiagram.puml
  docs/images/MarkRoomsUncleanActivityDiagram.png
Labels: documentation, priority.Medium, type.Task

#114 Add implementation of find command in developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/ProposedImplementationFindActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/ProposedImplementationFindActivityDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/bryanhce.md
  docs/team/jehousoh.md
  docs/team/kangzongxian.md
  docs/team/lan-jingbo.md
Labels: documentation, priority.Medium, type.Task

#111 Add request field
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/logic/parser/CliSyntax.java
  src/main/java/seedu/guest/logic/parser/ParserUtil.java
  src/main/java/seedu/guest/model/GuestBook.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/Request.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/storage/JsonAdaptedGuest.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalGuestGuestBook.json
  src/test/java/seedu/guest/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guest/model/util/SampleDataUtilTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#112 Add mark room unclean command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  guestbook.json
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/MarkRoomsUncleanCommand.java
  src/main/java/seedu/guest/logic/parser/GuestBookParser.java
  src/test/java/seedu/guest/logic/commands/MarkRoomsUncleanCommandTest.java
  src/test/java/seedu/guest/logic/parser/GuestBookParserTest.java
Labels: priority.Medium, type.Task

#118 Remove isRoomClean field from add command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/commands/MarkRoomsUncleanCommand.java
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
  src/main/java/seedu/guest/model/guest/IsRoomClean.java
  src/test/java/seedu/guest/logic/LogicManagerTest.java
  src/test/java/seedu/guest/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guest/model/guest/IsRoomCleanTest.java
  src/test/java/seedu/guest/testutil/GuestUtil.java
  src/test/java/seedu/guest/testutil/TypicalGuests.java
Labels: priority.Medium, type.Task

#117 Update DG with bill command, date range, model diagram, and acknowledgements
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BillActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BillActivityDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#119 Update GUI
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/index.md
  src/main/java/seedu/guest/commons/core/GuiSettings.java
  src/main/java/seedu/guest/ui/GuestCard.java
  src/main/java/seedu/guest/ui/UiManager.java
  src/main/resources/images/bill.png
  src/main/resources/images/dateRange.png
  src/main/resources/images/email.png
  src/main/resources/images/group.png
  src/main/resources/images/guest_book.png
  src/main/resources/images/isRoomClean.png
  src/main/resources/images/phone.png
  src/main/resources/images/request.png
  src/main/resources/images/room.png
  src/main/resources/images/roomClean.png
  src/main/resources/images/roomUnclean.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GuestListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Task

#116 logic appendix(manual testing) proposed implementation in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: documentation, priority.Medium, type.Task

#122 Update add guest in user guide
  docs/UserGuide.md
Labels: documentation, priority.Medium

#121 Improve search
  docs/UserGuide.md
  docs/images/findAlex9927275803-68.png
  src/main/java/seedu/guest/commons/util/StringUtil.java
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/commands/FindCommand.java
  src/main/java/seedu/guest/logic/parser/FindCommandParser.java
  src/main/java/seedu/guest/model/guest/GuestContainsKeywordsPredicate.java
  src/main/java/seedu/guest/model/guest/NameContainsKeywordsPredicate.java
  src/main/resources/view/GuestListCard.fxml
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/commands/FindCommandTest.java
  src/test/java/seedu/guest/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/guest/logic/parser/GuestBookParserTest.java
  src/test/java/seedu/guest/model/ModelManagerTest.java
  src/test/java/seedu/guest/model/guest/GuestContainsKeywordsPredicateTest.java
  src/test/java/seedu/guest/model/guest/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium, type.Task

#124 Update user guide to reflect current features in our application
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, priority.Medium, type.Task

#125 Add editing function for request part
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/logic/parser/EditCommandParser.java
  src/test/java/seedu/guest/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guest/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guest/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guest/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/guest/testutil/GuestUtil.java
Labels: priority.Medium, type.Task

#128 Update result display
  docs/UserGuide.md
  src/main/java/seedu/guest/ui/ResultDisplay.java
Labels: priority.Medium, type.Task

#126 Update DG(Small Error)
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation, priority.Medium

#129 Add glossary to user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#130 Add functionality to make sure guests' rooms are unique to each guest
  src/main/java/seedu/guest/logic/commands/AddCommand.java
  src/main/java/seedu/guest/logic/commands/EditCommand.java
  src/main/java/seedu/guest/model/GuestBook.java
  src/main/java/seedu/guest/model/Model.java
  src/main/java/seedu/guest/model/ModelManager.java
  src/main/java/seedu/guest/model/guest/Guest.java
  src/main/java/seedu/guest/model/guest/UniqueGuestList.java
  src/main/java/seedu/guest/model/guest/exceptions/RoomOccupiedException.java
  src/test/java/seedu/guest/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/guest/logic/commands/AddCommandTest.java
  src/test/java/seedu/guest/logic/commands/EditCommandTest.java
  src/test/java/seedu/guest/testutil/GuestBuilder.java
Labels: priority.Medium, type.Task

#131 Update UG and UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiComponentLabels.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/guest/model/guest/Request.java
  src/main/java/seedu/guest/model/util/SampleDataUtil.java
  src/main/java/seedu/guest/ui/HelpWindow.java
  src/main/resources/view/GuestListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: documentation, priority.Medium, type.Task

#132 Update user and developer guide to reflect our current implementations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FindActivityDiagram.png
  docs/images/ProposedImplementationFindActivityDiagram.png
Labels: documentation, priority.Medium, type.Task

#133 Add to introduction of UG
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#134 Update find
  docs/UserGuide.md
  src/main/java/seedu/guest/commons/util/StringUtil.java
  src/main/java/seedu/guest/model/guest/GuestContainsKeywordsPredicate.java
  src/test/java/seedu/guest/commons/util/StringUtilTest.java
  src/test/java/seedu/guest/model/guest/GuestContainsKeywordsPredicateTest.java
Labels: type.Bug, priority.Medium

#137 Make duplicate room issue start with a default guestbook
  src/main/java/seedu/guest/storage/JsonSerializableGuestBook.java
Labels: priority.Medium, type.Task

#135 Implement length validation for phone and email fields and increase size of UG logo
  docs/UserGuide.md
  docs/images/guest_book_320.png
  src/main/java/seedu/guest/model/guest/Bill.java
  src/main/java/seedu/guest/model/guest/DateRange.java
  src/main/java/seedu/guest/model/guest/Email.java
  src/main/java/seedu/guest/model/guest/Name.java
  src/main/java/seedu/guest/model/guest/NumberOfGuests.java
  src/main/java/seedu/guest/model/guest/Phone.java
  src/main/java/seedu/guest/model/guest/Request.java
  src/main/java/seedu/guest/model/guest/Room.java
  src/test/java/seedu/guest/model/guest/EmailTest.java
  src/test/java/seedu/guest/model/guest/PhoneTest.java
Labels: documentation, priority.Medium, type.Task

#138 Update ug command summary more feature quick start
  docs/UserGuide.md
  docs/images/Download.png
  docs/images/GuestBookIcon.png
  docs/images/download2.png
Labels: documentation, priority.Medium

#140 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/Download.png
  docs/images/DownloadInstruction.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#139 Update validation constants
  src/main/java/seedu/guest/model/guest/Email.java
  src/main/java/seedu/guest/model/guest/NumberOfGuests.java
  src/main/java/seedu/guest/model/guest/Phone.java
  src/main/java/seedu/guest/model/guest/Request.java
Labels: priority.Medium, type.Task

#141 Fix billCommand bug
  src/main/java/seedu/guest/commons/util/StringUtil.java
  src/main/java/seedu/guest/logic/commands/BillCommand.java
  src/test/java/seedu/guest/logic/commands/BillCommandTest.java
Labels: type.Bug, priority.Medium

#142 Update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#144 Fix room error message
  src/main/java/seedu/guest/model/guest/Room.java
Labels: type.Bug, priority.Low

#145 Remove unnecessary commands
  docs/UserGuide.md
Labels: priority.Medium

#146 Add exit command to command summary
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#147 Update User Guide
  docs/UserGuide.md
  docs/images/GuestBookIcon.png
Labels: documentation, priority.Medium, type.Task

#152 Add code reuse portion
  src/main/java/seedu/guest/model/guest/Room.java
Labels: priority.Medium, type.Task

#151 Update UG table
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/bill.png
  docs/images/dateRange.png
  docs/images/email.png
  docs/images/group.png
  docs/images/guest_book_160.png
  docs/images/isRoomClean.png
  docs/images/phone.png
  docs/images/request.png
  docs/images/room.png
Labels: documentation, priority.Medium, type.Task

#148 Add subheadings and edit introduction
  docs/UserGuide.md
Labels: documentation, type.Task, severity.Medium

#188 Handle bold and boxing after bill in UG
  docs/UserGuide.md
Labels: documentation, priority.Low

#189 Update PPP and UG
  docs/UserGuide.md
  docs/team/bryanhce.md
Labels: documentation, severity.Medium

#187 Emphasise keywords and rephrase awkward sentences in UG up to Bill command
  docs/UserGuide.md
Labels: documentation, priority.Low, type.Task

#191 Standardise the UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#192 Fix numbering of list and space formatting
  docs/UserGuide.md
Labels: documentation, priority.Medium

#190 Simplify code in AddCommandParser
  src/main/java/seedu/guest/logic/parser/AddCommandParser.java
Labels: priority.Medium, type.Task

#193 Update title to be GuestBook
  docs/_config.yml
Labels: documentation, priority.Low

#194 Update my ppp
  docs/team/kangzongxian.md
Labels: priority.Low

#197 Correct some typos in PPP
  docs/team/kangzongxian.md
Labels: documentation, priority.Low, type.Task
